# Generated by Django 5.0.6 on 2024-06-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Наличными", "Наличными"), ("Без наличный", "Без наличный")],
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
