# Generated by Django 5.0.6 on 2024-07-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_sum",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Наличными", "Наличными"), ("Без наличный", "Без наличный")],
                default="card",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
